const ATTENDEES_DELETE = 'ATTENDEES_DELETE';
const ATTENDEES_ADD = 'ATTENDEES_ADD';
const ATTENDEES_EDIT = 'ATTENDEES_EDIT';
const ATTENDEES_ADD_FROM_XLXS = 'ATTENDEES_ADD_FROM_XLXS';

export { ATTENDEES_ADD, ATTENDEES_DELETE, ATTENDEES_EDIT, ATTENDEES_ADD_FROM_XLXS };
