const EVALUATIONS_ADD = 'EVALUATIONS_ADD';
const EVALUATIONS_DELETE = 'EVALUATIONS_DELETE';
const EVALUATIONS_EDIT = 'EVALUATIONS_EDIT';
const EVALUATIONS_UNBIND_QUESTIONS = 'EVALUATIONS_UNBIND_QUESTIONS';
const EVALUATIONS_BIND_QUESTIONS = 'EVALUATIONS_BIND_QUESTIONS';

export {
  EVALUATIONS_ADD,
  EVALUATIONS_EDIT,
  EVALUATIONS_DELETE,
  EVALUATIONS_UNBIND_QUESTIONS,
  EVALUATIONS_BIND_QUESTIONS
};
