const GROUPS_ADD = 'GROUPS_ADD';
const GROUPS_DELETE = 'GROUPS_DELETE';
const GROUPS_EDIT = 'GROUPS_EDIT';
const GROUPS_UNBIND_ATTENDEES = 'GROUPS_UNBIND_ATTENDEES';
const GROUPS_BIND_ATTENDEES = 'GROUPS_BIND_ATTENDEES';
const GROUPS_ADD_FROM_XLXS = 'GROUPS_ADD_FROM_XLXS';

export {
  GROUPS_ADD,
  GROUPS_DELETE,
  GROUPS_UNBIND_ATTENDEES,
  GROUPS_BIND_ATTENDEES,
  GROUPS_EDIT,
  GROUPS_ADD_FROM_XLXS
};
