const INSTITUTIONS_DELETE = 'INSTITUTIONS_DELETE';
const INSTITUTIONS_ADD = 'INSTITUTIONS_ADD';
const INSTITUTIONS_EDIT = 'INSTITUTIONS_EDIT';
const INSTITUTIONS_SELECT = 'INSTITUTIONS_SELECT';

export { INSTITUTIONS_ADD, INSTITUTIONS_DELETE, INSTITUTIONS_SELECT, INSTITUTIONS_EDIT };
