const REPOSITORIES_ADD = 'REPOSITORIES_ADD';
const REPOSITORIES_DELETE = 'REPOSITORIES_DELETE';
const REPOSITORIES_EDIT = 'REPOSITORIES_EDIT';

export { REPOSITORIES_ADD, REPOSITORIES_DELETE, REPOSITORIES_EDIT };
